# Generated by Django 5.0.6 on 2024-11-09 12:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='waste_images/')),
                ('Description', models.TextField()),
                ('Location', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], max_length=50)),
                ('SubmissionDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ResolutionDate', models.DateTimeField(blank=True, null=True)),
                ('AssignedTo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='ecotrak.usertable')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ecotrak.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('FeedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('Comment', models.TextField()),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1)),
                ('DateSubmitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('ResponseStatus', models.BooleanField(default=False)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecotrak.usertable')),
            ],
        ),
    ]
