# Generated by Django 5.0.6 on 2024-11-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrak', '0003_wastereport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastereport',
            name='id',
        ),
        migrations.AddField(
            model_name='wastereport',
            name='ReportID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
