# Generated by Django 5.0.6 on 2024-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrak', '0004_remove_wastereport_id_wastereport_reportid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastereport',
            name='ReportID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
