# Generated by Django 5.0.6 on 2024-12-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecotrak', '0006_alter_wastereport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='anonymous@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default='No feedback provided'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='usertable',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
